### PR TITLE
Layout tweaks

### LINKED ISSUE #245: Program Registration content cut off by "toggle map" button in mobile view
Reference documents
[V2](http://ppr-finder-v2.surge.sh)
[Testing protocol](https://docs.google.com/document/d/1OFYL4GYWQ-RogzCmpMYQ5Gm0Vmhr9AJg-I4sbeMIQsU/edit#heading=h.7l4ueyblveo1)
Data: myppr (production database)
Data download date: 5/18/2018

### Observed Behavior

Go to any activity details view using iPhone SE.
Scroll to the bottom.

### Screenshot
[Screen recording](https://www.dropbox.com/s/8aafh39najgfo0a/Cant%20see%20bottom%20of%20activity%20details%20view.MP4?dl=0)

### LINKED ISSUE #246: Not able to view at least one complete category card in mobile view
[Testing protocol](https://docs.google.com/document/d/1OFYL4GYWQ-RogzCmpMYQ5Gm0Vmhr9AJg-I4sbeMIQsU/edit#heading=h.1znmxbrm4710) - version 2
http://ppr-finder-v2.surge.sh
Data: myppr (production database)
Data download date: 5/18/2018

### Observed Behavior
View activity or locations category view in iPhone SE.
There is not enough vertical screen real estate to render at least one activity or location category card.

### Screenshot
cant see one entire category card
cant see one entire category card2

### LINKED ISSUE #259: Modal on mobile allows user to scroll past it
Reference documents
[Spec. Doc.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view?usp=sharing)  | 
[Testing protocol](https://docs.google.com/document/d/1duzm6Nj914sYiUyMSUSoKMWFETPy3C5XSajTEyI5pAs/edit?usp=sharing)

1. Open the finder v2 on mobile
2. Open the modal (via the menu)
3. Scroll down

You end up getting to the map, with the modal above you. Not sure I'd call this critical, just a css bug.

### PR DESCRIPTION
**Pull request by karissademi**
* Prevents map from appearing behind header when user attempts to scroll on iOS devices. Closes #245 
* Decreases height of images and adjusts layout for small screens. Closes #246 
* Prevents map from appearing beneath mobile menu if user scrolls. Closes #259

### CODE REVIEW

File: src/pages/Activities.vue [hunk 1]
```diff
@@ -38,7 +38,9 @@
       Toggle map
     </button>
     <section class="map">
-      <SiteMap :activities="filteredActivities"/>
+      <SiteMap
+        v-if="$mq == 'lg' || !isSidebarVisible"
```
Comment (timwis) [inline src/pages/Activities.vue]: We should probably use the strict equality operator `===` instead of the loose one `==` ([background](https://codeburst.io/javascript-double-equals-vs-triple-equals-61d4ce5a121a)). Going further, perhaps this dual-condition should be a computed property -- would that improve readability? Going _one step further_, I wonder if we should change the name of the variable `isSidebarVisible` to something like `isMapVisible` at this point, since it's only modified by `toggleMap`, and the check we're doing is whether it's false. Would it be more readable if the variable were `isMapVisible`?

File: src/pages/SearchResults.vue [hunk 2]
```diff
@@ -65,11 +65,11 @@
     </button>
     <section class="map">
       <SiteMap
-        v-if="activeTab === 'activities'"
+        v-if="(activeTab === 'activities') && ($mq == 'lg' || !isSidebarVisible)"
```
Comment (timwis) [inline src/pages/SearchResults.vue]: These lines would be another good candidate for computed properties, since there's 3 conditions in the markup.
