### PR TITLE
Display facility schedules

### LINKED ISSUE #84: Facility schedules are not rendering on facility details views
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/athletic |  0.1.0 | Chrome - 1024 x 768 |  Desktop

### Expected Behavior

Facility schedules render on facility details views under the heading"regular schedules".

### Observed Behavior
No facility schedules are rendered on facility details view.

#### Proposed Solution
Pull content from MyPPR.FacilitySchedule table to populate on facility details view.

### Screenshot
image

### PR DESCRIPTION
**Pull request by karissademi**
Closes #84

### CODE REVIEW

File: src/sources/PPRFQueryBuilder.js [hunk 1]
```diff
@@ -34,6 +34,7 @@ const DATE_FORMAT = 'Month DD, YYYY'
  */
 export default class PPRFQuery {
   constructor (build) {
+    console.log(build)
```
Comment (timwis) [inline src/sources/PPRFQueryBuilder.js]: I think you left this in by accident

File: src/sources/api.js [hunk 2]
```diff
@@ -113,16 +113,18 @@ class API {
...
    * and all the programs at that facility
-   * @param  {string} facilityID faciity entity id
+   * @param  {string} facilityID facility entity id
    *
    * @return {object}            Promise
    *
    * @since 0.1.0
    */
   getFacilityByID (facilityID) {
+    console.log(facilityID)
```
Comment (timwis) [inline src/sources/api.js]: I think you left this in by accident

File: src/containers/sidebar/pprf-sidebar-location-detail-container.vue [hunk 3]
```diff
@@ -116,20 +131,34 @@ export default {
...
+          // map days to each schedule
+          for (var i = 0; i < facilitySchedules.length; i++) {
+            // find the days records from our cached days table in local storage
+            facilitySchedules[i].days = facilitySchedules[i].days.map(day => _.findWhere(LocalCacheManager.getRow('daysTable'), {id: day}))
+          }
+          vm.facilitySchedules = facilitySchedules
+
+          if (results[0].data.rows[0].location_contact_name) {
+            /* eslint-disable no-eval */
+            var parsedJSON = eval('(' + results[0].data.rows[0].location_contact_name + ')')
```
Comment (timwis) [inline src/containers/sidebar/pprf-sidebar-location-detail-container.vue]: Oh yikes, didn't notice this before in the previous version, but this may create an XSS vulnerability. Why are we using `eval` here? Can we do without it?

File: src/containers/sidebar/pprf-sidebar-location-detail-container.vue [hunk 4]
```diff
@@ -116,20 +131,34 @@ export default {
 
   beforeRouteEnter (to, from, next) {
     api.getFacilityByID(to.params.facility_id)
```
Comment (timwis) [inline src/containers/sidebar/pprf-sidebar-location-detail-container.vue]: Hm, I wonder why this was put here instead of firing an action, which would put the results into state, and then we'd use mapState to access the results. Well, it was like this before too.

File: src/containers/sidebar/pprf-sidebar-location-detail-container.vue [hunk 5]
```diff
@@ -116,20 +131,34 @@ export default {
...
-            vm.$store.dispatch('setMapMarkers', { entityType: 'facility' })
-          })
+      .then(results => {
+        next(vm => {
+          let facilitySchedules = results[2].data.rows
+
+          // map days to each schedule
+          for (var i = 0; i < facilitySchedules.length; i++) {
+            // find the days records from our cached days table in local storage
+            facilitySchedules[i].days = facilitySchedules[i].days.map(day => _.findWhere(LocalCacheManager.getRow('daysTable'), {id: day}))
```
Comment (timwis) [inline src/containers/sidebar/pprf-sidebar-location-detail-container.vue]: How/why does the local cache get populated with days?

File: src/sources/api.js (hunk 2 above)
Comment (karissademi) [reply src/sources/api.js]: Indeed!

**Comment by timwis** [comment]
btw, I didn't notice the `[WIP]` in the title - sorry for jumping the gun on a review :P

**Comment by karissademi** [comment]
I just added it. :) There are still some style tweaks and clean up to do!

File: src/containers/sidebar/pprf-sidebar-location-detail-container.vue (hunk 4 above)
Comment (karissademi) [reply src/containers/sidebar/pprf-sidebar-location-detail-container.vue]: I'm ok with leaving it as is, at least for the time being. I think we have higher priority items to cross off.

File: src/containers/sidebar/pprf-sidebar-location-detail-container.vue (hunk 5 above)
Comment (karissademi) [reply src/containers/sidebar/pprf-sidebar-location-detail-container.vue]: The local cache gets populated on initialization, with data from the PPR Days table. I assume this is done for performance reasons, so API call doesn't need to be made more than once. It's used for filters and program schedules.

File: src/containers/sidebar/pprf-sidebar-location-detail-container.vue [hunk 6]
```diff
@@ -143,8 +144,7 @@ export default {
           vm.facilitySchedules = facilitySchedules
 
           if (results[0].data.rows[0].location_contact_name) {
-            /* eslint-disable no-eval */
-            var parsedJSON = eval('(' + results[0].data.rows[0].location_contact_name + ')')
+            var parsedJSON = JSON.parse(results[0].data.rows[0].location_contact_name.replace(/'/g, '"'))
```
Comment (timwis) [inline src/containers/sidebar/pprf-sidebar-location-detail-container.vue]: Much better than eval -- thanks! I'm not sure what the data it's parsing looks like, but if it's ever invalid JSON, this will fail ungracefully -- if there's a chance of that, I recommend wrapping this in a try/catch block and gracefully handling the error (perhaps doing nothing). Other than that, LGTM!

File: src/containers/sidebar/pprf-sidebar-location-detail-container.vue [hunk 7]
```diff
@@ -116,20 +132,34 @@ export default {
...
+          let facilitySchedules = results[2].data.rows
+
+          // map days to each schedule
+          for (var i = 0; i < facilitySchedules.length; i++) {
+            // find the days records from our cached days table in local storage
+            facilitySchedules[i].days = facilitySchedules[i].days.map(day => _.findWhere(LocalCacheManager.getRow('daysTable'), {id: day}))
+          }
+          vm.facilitySchedules = facilitySchedules
+
+          try {
```
Comment (timwis) [inline src/containers/sidebar/pprf-sidebar-location-detail-container.vue]: This looks great

Comment (timwis) [reply src/containers/sidebar/pprf-sidebar-location-detail-container.vue]: Oh, alternatively we can cast it to json in the database (`select location_contact_name::json`) but might have the same issue as I mentioned in the other PR

Comment (karissademi) [reply src/containers/sidebar/pprf-sidebar-location-detail-container.vue]: The string coming back isn't valid json. There are single quotes around the key and value, instead of double quotes. Casting it just throws the `invalid input syntax for type json` error. Same goes with the other PR. I'm not sure how much control we have over the data source, but I agree it should be corrected there.

File: src/containers/sidebar/pprf-sidebar-location-detail-container.vue (hunk 5 above)
Comment (karissademi) [reply src/containers/sidebar/pprf-sidebar-location-detail-container.vue]: Just noticed that the weekday data coming back from the API is just a string of numbers. The local cache maps day of the week nice names to those numbers.

**Comment by sarahall** [comment]
@karissademi lgtm 
@timwis what are your thoughts?
